import type { APIRoute } from 'astro';
import { getCollection } from 'astro:content';

export const prerender = false;

// The folders a new page can be filed under. Derived from the content
// collection rather than stored anywhere: the sidebar is autogenerated from
// the folder structure, so the folders that exist ARE the sections.
export const GET: APIRoute = async (ctx) => {
	if (!ctx.locals.user) return new Response('Sign in to edit', { status: 401 });

	const entries = await getCollection('docs');
	const sections = new Set<string>();

	for (const entry of entries) {
		// filePath is src/content/docs/<section>/<name>.md, or no section at
		// all for a top-level page. Anything nested deeper is not offered:
		// nothing nests today, and a picker is the wrong place to invent it.
		const parts = (entry.filePath ?? '').split('/').slice(3, -1);
		if (parts.length === 1) sections.add(parts[0]);
	}

	return Response.json({ sections: [...sections].sort() });
};
