// Regenerates migrations/0001_auth.sql from the *installed* better-auth.
//
// Do not use `npx @better-auth/cli` - that package is deprecated and stuck on
// 1.4, and generates a schema the 1.7 runtime rejects (missing account.issuer).
// This uses better-auth's own migration engine at whatever version is in
// node_modules, so the schema can't drift from the runtime.
//
// Run: npm run gen:auth-schema   (and re-run it whenever a plugin is added)
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { getMigrations } from 'better-auth/db/migration';
import { passkey } from '@better-auth/passkey';

const OUT = 'migrations/0001_auth.sql';
/** Reference output when drift is found. Deliberately NOT in migrations/:
 *  anything ending .sql in there is a migration to wrangler and to this
 *  script's own comparison. */
const DRIFT = '.auth-schema.generated.sql';

// Must mirror the plugin list in src/lib/auth.ts. Only the plugins affect the
// schema; their runtime options (rpID, secrets) do not.
const { compileMigrations } = await getMigrations({
	database: new DatabaseSync(':memory:'),
	socialProviders: {
		discord: { clientId: 'x', clientSecret: 'x' },
		github: { clientId: 'x', clientSecret: 'x' },
	},
	plugins: [passkey({})],
});

const sql = await compileMigrations();
const header = [
	'-- Generated by scripts/gen-auth-schema.ts - do not edit by hand.',
	'--',
	'-- Once this has been applied to a database, DO NOT regenerate it: wrangler',
	'-- tracks migrations by filename, so an edit here never reaches a database',
	'-- that already ran it. Re-running the script then only reports drift.',
	'-- Absorb a better-auth schema change with a NEW migrations/000N_*.sql.',
].join('\n');

if (!existsSync(OUT)) {
	writeFileSync(OUT, `${header}\n${sql}\n`);
	console.log(`wrote ${OUT}`);
	process.exit(0);
}

// Past the first apply this script DETECTS drift, it does not write. 0001 has
// been applied to real databases and wrangler tracks migrations by filename,
// so rewriting it would leave every migrated database on the old schema while
// the file claimed otherwise - which is how better-auth 1.7.5's dropped
// `account.issuer` column nearly shipped a broken deploy.
//
// The comparison is against every migration applied in order, not against
// 0001 alone: a later migration is the correct way to absorb a schema change,
// and comparing to 0001 would report drift forever once one exists.
const columns = (db: DatabaseSync, table: string) =>
	db
		.prepare(`select name, type, "notnull", dflt_value, pk from pragma_table_info(?) order by name`)
		.all(table)
		.map((c) => JSON.stringify(c))
		.join(',');

const load = (db: DatabaseSync, statements: string) => {
	for (const statement of statements.split(';')) {
		if (statement.trim() && !statement.trim().startsWith('--')) db.exec(statement);
	}
	return db;
};

const stripComments = (text: string) =>
	text.split('\n').filter((l) => !l.trim().startsWith('--')).join('\n');

const want = load(new DatabaseSync(':memory:'), sql);
const have = load(
	new DatabaseSync(':memory:'),
	readdirSync('migrations')
		// Numbered files only, in order - the same set wrangler applies.
		.filter((f) => /^\d+_.*\.sql$/.test(f))
		.sort()
		.map((f) => stripComments(readFileSync(`migrations/${f}`, 'utf8')))
		.join(';\n'),
);

const tables = want
	.prepare(`select name from sqlite_master where type = 'table' order by name`)
	.all()
	.map((r) => String(r.name));

const drift = tables.filter((t) => columns(want, t) !== columns(have, t));

if (drift.length === 0) {
	console.log(`migrations/ match the installed better-auth (${tables.length} tables checked).`);
} else {
	writeFileSync(DRIFT, `${header}\n-- NOT a migration. Reference only.\n${sql}\n`);
	console.error(`\nSchema drift in: ${drift.join(', ')}`);
	for (const t of drift) {
		console.error(`\n  ${t}\n    want: ${columns(want, t)}\n    have: ${columns(have, t)}`);
	}
	console.error(`\nbetter-auth wants a schema migrations/ does not produce.`);
	console.error(`Add a NEW migrations/000N_*.sql. Do NOT edit ${OUT}. Reference: ${DRIFT}\n`);
	process.exitCode = 1;
}
